
OLED_ENABLE = yes
OLED_DRIVER = SSD1306
ENCODER_ENABLE = yes
CONSOLE_ENABLE = no
EXTRAKEY_ENABLE = yes

MOUSEKEY_ENABLE = yes        # Mouse keys(+4700)
LTO_ENABLE = yes

COMBO_ENABLE = yes
LEADER_ENABLE = yes
