#pragma once
//#define TAPPING_FORCE_HOLD
#define TAPPING_TERM 155
// #define TAPPING_TERM_PER_KEY
#define PERMISSIVE_HOLD
// #define PERMISSIVE_HOLD_PER_KEY

#define COMBO_COUNT 28
#define COMBO_TERM 17
#define LEADER_TIMEOUT 500

#define IGNORE_MOD_TAP_INTERRUPT
#define TAPPING_FORCE_HOLD
#define TAPPING_FORCE_HOLD_PER_KEY
