#pragma once
//#define TAPPING_FORCE_HOLD
#define TAPPING_TERM 160
#define TAPPING_TERM_PER_KEY
// #define PERMISSIVE_HOLD
// #define PERMISSIVE_HOLD_PER_KEY
// #define HOLD_ON_OTHER_KEY_PRESS_PER_KEY

#define COMBO_COUNT 30
#define COMBO_TERM 17
#define LEADER_TIMEOUT 500

// #define IGNORE_MOD_TAP_INTERRUPT
#define IGNORE_MOD_TAP_INTERRUPT_PER_KEY

// #define RETRO_TAPPING_PER_KEY
// #define TAPPING_FORCE_HOLD
#define TAPPING_FORCE_HOLD_PER_KEY
